Revert "Use functools.wraps in util.py"
This does not work very well with Python 2.x, where one can get:
  AttributeError: _ProxyMethod instance has no attribute '__name__'.

This reverts commit 93442eb43c215a5f04e0ca2d72360e200b10c55e.